sudo: false

branches:
  only:
  - master
  - development

language: scala

scala:
- 2.12.8

script:
- sbt ++$TRAVIS_SCALA_VERSION test

jdk:
- oraclejdk8
- openjdk8

notifications:
  email:
  - x@wayfarerx.net